### ISSUE TITLE
Not sure how this works

### ISSUE THREAD

**Issue by Mystiirion** [ExpeditionRPG/expedition-cards#39]
Please make a Google sheet example of how to make the cards because the instructions given are pretty vague and whenever I tried to post it on the card creator page it doesn't show anything despite the fact that I've disabled AdBlock and do everything you said

**Comment by toddmedema** [comment]
Updated the documentation with two things that should fix it for you:

1. Instead of copying the publish link, copy the link of the Google Sheet from your browser's URL bar.
2. Refresh after entering the source URL.

If this still doesn't work for you, it would be hugely helpful to send me a screen capture of you going through the flow, so that I can see what's going on :) todd@fabricate.io

https://github.com/ExpeditionRPG/expedition-cards/blob/master/CARD-CREATION.md
